language: python
sudo: required
install:
  - sudo apt-get install python python-mysqldb python-pip python-lxml python-requests python-dev
  - sudo apt-get install python-virtualenv virtualenvwrapper
  - source /etc/bash_completion
  - pip install virtualenv
  - sudo easy_install pip
  - sudo pip install --upgrade virtualenvwrapper
  - export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
  - export WORKON_HOME=$HOME/.virtualenvs
  - export PROJECT_HOME=$HOME/projects
  - source /usr/local/bin/virtualenvwrapper.sh
  - mkvirtualenv --system-site-packages yamdwe
  - pip install http://pypi.python.org/packages/source/s/simplemediawiki/simplemediawiki-1.2.0b2.tar.gz
  - pip install -i http://pypi.pediapress.com/simple/ mwlib
  - pip install requests
script: 
  - workon yamdwe # multiple invokations don't hurt
  - python wikicontent_tests.py
